#!/usr/bin/env node
const execa = require('execa');
const argv = require('yargs').argv;
const invokeArgs = require('./tests/e2e/invokeArgs');

(async () => {
  let projectName = 'dev';
  if (argv.tests) projectName = 'tests';
  if (argv.base) projectName = 'base';

  // Create project
  await execa(
    '../node_modules/.bin/vue',
    [
      'create',
      '--inlinePreset',
      JSON.stringify({
        plugins: {
          '@vue/cli-plugin-babel': {},
        },
        router: true,
        vuex: true,
      }),
      '--force',
      '--git',
      'false',
      projectName,
    ],
    {
      cwd: 'packages',
      stdio: 'inherit',
    },
  );

  // Add VueNeue plugin
  if (!argv.base) {
    await execa(
      '../../node_modules/.bin/vue',
      ['add', '@vueneue/ssr', ...invokeArgs],
      {
        cwd: `packages/${projectName}`,
        stdio: 'inherit',
      },
    );
  }

  await execa('./node_modules/.bin/lerna', ['link']);
})();
