#!/usr/bin/env node
const fs = require('fs-extra');
const argv = require('yargs').argv;
const { join } = require('path');
const execa = require('execa');
const waitOn = require('wait-on');
const os = require('os');
const { execSync } = require('child_process');
const Workspace = require('./utils/Workspace');

const ws = new Workspace(join(__dirname, '..'));
const projects = require('./projects.json');

const waitOnPromise = options => {
  return new Promise(resolve => waitOn(options, resolve));
};

(async () => {
  if (!(await fs.exists(join(ws.packagesPath, 'base/package.json')))) {
    await ws.createBaseProject();
  }

  const [command, name] = argv._;

  switch (command) {
    case 'link':
      await ws.relink('@vueneue/vue-cli-plugin-ssr');
      await ws.relink('@vueneue/ssr-core');
      await ws.relink('@vueneue/ssr-server');
      return;
  }

  const project = ws.getProject(name);

  let server;

  // Force Yarn
  await ws.vue(['config', '-s', 'packageManager', 'yarn'], {
    stdio: 'inherit',
  });

  switch (command) {
    case 'create':
      await project.create();
      const { plugins, deps, mocks } = projects[name] || {};
      await project.addPlugin(plugins);
      await project.addDependency(deps);

      if (!argv.noInvoke) {
        await project.invokePlugin('@vueneue/ssr', ['--docker', '0']);
      }

      await ws.relink('@vueneue/vue-cli-plugin-ssr');

      if (mocks) await fs.copy(mocks, project.path);
      break;

    case 'serve':
      project.cliService('ssr:serve');
      break;

    case 'build':
      project.cliService('ssr:build');
      break;

    case 'start':
      project.cliService('ssr:start');
      break;

    case 'test':
      if (!argv.prod) {
        server = project.cliService('ssr:serve', [], {
          stdio: 'inherit',
        });
      } else {
        await project.cliService('ssr:build', ['--mode', 'production']);
        server = project.cliService('ssr:start', ['--mode', 'prodction'], {
          stdio: 'inherit',
        });
      }

      await waitOnPromise({
        resources: [`tcp:localhost:8080`],
        timeout: 60 * 1000,
      });

    case 'test:run':
      const jestArgs = process.argv.slice(4);

      const prodIndex = jestArgs.findIndex(arg => arg === '--prod');
      if (prodIndex >= 0) jestArgs.splice(prodIndex, 1);

      const jest = execa(
        './node_modules/.bin/jest',
        ['--config', `tests/specs/${name}/config.js`, ...jestArgs],
        {
          stdio: 'inherit',
        },
      );

      jest.on('exit', exitCode => {
        console.log(`Exit code: ${exitCode}`);
        if (server) {
          if (os.platform() === 'win32') {
            execSync(`taskkill /F /T /PID ${server.pid}`);
          } else {
            server.kill('SIGTERM');
          }
        }

        process.exit(exitCode);

        if (os.platform() === 'win32') {
          execSync(`taskkill /F /T /PID ${process.pid}`);
        }
      });
      break;
  }
})().catch(err => {
  console.error(err);
  process.exit(1);
});
